return {
    crosshair = "guns/blick_crosshair.png",
    body = "guns/blick_body.png",
    firingSound = "guns/blick.mp3",
    muzzleFlashTexture = "guns/blick_flash.png",
    bodyOffsetX = -3,
    bodyOffsetY = -0,
    screenshake = 2,
    recoilX = 10,
    recoilY = 0,
    recoilXDecay = 0.1,
    recoilYDecay = 0,
    recoilRotation = 0.7,
    recoilRotationDecay = 0.05,
    maxRecoilX = 20,
    maxRecoilY = 0,
    maxRecoilRotation = 1,
    bulletOffsetX = 32,
    bulletOffsetY = 10
}